global:
  scrape_interval: 5s

scrape_configs:
  # =========================
  # FastAPI inference service
  # =========================
  - job_name: "road-mark-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  # =========================
  # MLflow (optional)
  # =========================
  # - job_name: "mlflow"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["mlflow:5000"]
